[build]
  command = "if [ -d flutter ]; then flutter/bin/flutter upgrade; else git clone https://github.com/flutter/flutter.git -b stable --depth 1; fi && export PATH=$PATH:`pwd`/flutter/bin && flutter pub get && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"